##########################################
### SAMPLE
##########################################

# User
userId: "<samplify userId>"  # e.g. userid: "kolart"
userEmail: "<userEmail>"     # e.g. userEmail: "kolart@uw.edu"

# Sample
sampleDirectory: "<full path to sample directory>"    # e.g. sampleDirectory: "/net/nwgc/vol1/data/processed/samples/123456/WHOLE_GENOME"
sampleQCDirectory: "<full path to sample QC directory>"  # e.g. sampleQCDirectory: "/net/nwgc/vol1/data/processed/samples/123456/WHOLE_GENOME/qc"
sampleId: <samplify sampleId>  # e.g sampleId: 123456

# Target
sequencingPlatform: "<name of sequencing platform (PacBio or ONT)"   		# e.g. sequencingPlatform: "PacBio"
sequencerType: "<name of sequencer type (Sequel or Revio or Promethion)>"   # e.g. sequencerType: "Revio"
sequencingTarget: "<name of sequencing target>"   							# e.g. sequencingTarget: "WHOLE_GENOME"

# Reference Genome
referenceGenome: "<full path to reference genome fasta>"    # e.g. referenceGenome: "/net/nwgc/vol1/references/human/grc38/genome/pacbio/human_GRCh38_no_alt_analysis_set.fasta"

# Fingerprint Bed
fingerprintBed: "<full path to fingerprint bed>"    # e.g. fingerprintBed: "/net/nwgc/vol1/references/human/grc38/targets/fingerprint_grc38_aou.bed"

##########################################
### DATA INPUT - Only one fo the following should be used (hifiBams, ontFastqsFolder, mergedBam) 
##########################################

# HiFI Bams (for PacBio)
hiFiBams:
  - "<full path to first hiFiBam>"
  - "<full path to second hiFiBam>"
  - "<repeat for more hiFiBams>"
# e.g.
#hiFiBams:
#  - "/net/nwgc/vol1/home/kolart/nextflow_pb_test/ccs1-2_downsampled.bam"
#  - "/net/nwgc/vol1/home/kolart/nextflow_pb_test/ccs2-2_downsampled.bam"

ontReleaseData: <boolean to release data> # e.g. ontReleaseData: true
# perform QC on the SUP data and release after sequencing complete == true
# e.g. ontReleaseData: false
# non-release operations; i.e. perform QC on the HAC data

ontSetupBasecall: <boolean to basecall setup>
# e.g. ontSetupBasecall: true
# to perform the setup only but not further QC steps
# e.g. ontSetupBasecall: false
# do not perform the setup, but perform the HAC QC steps only
# e.g. not defining the parameter
# perform both the setup and also the HAC QC steps

# ONT Fast5/Pod5Folders (for ONT)
ontDataFolder: "<full path to the directory for ont data output>" # e.g. ontDataFolder: "/net/nwgc/vol1/home/kolart/nextflow_ont_test/ont"
ontBaseCall: <boolean to perform base call> # e.g. ontBaseCall: true
                                            # e.g. ontBaseCall: false
ontBaseCallModel: "<dorado model>" # e.g. ontBaseCallModel: "dna_r10.4.1_e8.2_400bps_sup@v3.5.2"
                                   # e.g. ontBaseCallModel: "dna_r9.4.1_e8_sup@v3.3"
ontBaseCallBaseModifications: "<dorado base modifications>" # e.g. ontBaseCallBaseModifications: "5mCG"
ontBaseCallOutFolder: "<full path to the directory for ont basecall output>" # e.g. ontDataFolder: "/net/nwgc/vol1/home/kolart/nextflow_ont_test/pod5_sup"

# ONT Fast5/Pod5Folders (for ONT)
# does not check for inconsistency
ontSignalFolders:
 -  "<full path to first folder that contains the fast5s>"
 -  "<full path to second folder that contains the fast5s>"
 -  "<full path to first folder that contains the pod5s>"
 -  "<full path to second folder that contains the pod5s>"
 -  "<repeat for more folders>"
# e.g.
#ontSignalFolders: 
#  - "/net/nwgc/vol1/home/kolart/nextflow_ont_test/fast5s_1"
#  - "/net/nwgc/vol1/home/kolart/nextflow_ont_test/fast5s_2"
#  - "/net/nwgc/vol1/home/kolart/nextflow_ont_test/pod5s_1"
#  - "/net/nwgc/vol1/home/kolart/nextflow_ont_test/pod5s_2"


# ONT Fastq Folders(for ONT) / obsoleted
#ontFastqFolders:
# -  "<full path to first folder that contains the fastqs>"
# -  "<full path to second folder that contains the fastqs>"
# -  "<repeat for more folders>"
# e.g.
#ontFastqFolders: 
#  - "/net/nwgc/vol1/home/kolart/nextflow_ont_test/fastqs_1"
#  - "/net/nwgc/vol1/home/kolart/nextflow_ont_test/fastqs_2"

# ONT Fastq Folders(for ONT)
ontBamFolders:
 -  "<full path to first folder that contains the bams>"
 -  "<full path to second folder that contains the bamss>"
 -  "<repeat for more folders>"
# e.g.
#ontBamFolders: 
#  - "/net/nwgc/vol1/home/kolart/nextflow_ont_test/bams_1"
#  - "/net/nwgc/vol1/home/kolart/nextflow_ont_test/bams_2"

# mergedBam (for running qc on an already existing merged bam)
mergedBam: "<full path to a merged bam that contains nm tags>"  # e.g.  mergedBam: /net/nwgc/vol1/home/kolart/pacbio_merged_test.bam   


##########################################
### RabbitMQ
##########################################
rabbitHost: "<name of host for rabbitMQ>"				#e.g rabbitHost: "burnet"
registration_url: "<url to send rabbit message to>"		#e.g.registration_url: "http://burnet.gs.grid.washington.edu/samplify/RegisterPacBioMapMergeQCCompletion"
